/// <reference types="vite/client" />
import type { DataProvider, GetOneParams } from 'react-admin';

export type Health = { id: string; status: string; recorder_state: string; heartbeat_status: string; heartbeat_age_seconds?: number | null; current_health_issues: string[]; current_markets: Record<string, string | null>; observed_at?: string | null; uptime_seconds?: number | null; kalshi_ws_synchronized_count: number; kalshi_ws_connection_state: string; kalshi_ws_seq_gaps: number; };
export type Market = { id: string; asset: string; availability: string; ticker?: string | null; series?: string | null; target?: string | null; window_start?: string | null; window_end?: string | null; seconds_remaining?: number | null; lifecycle: string; official_status?: string | null; yes_bid?: string | null; yes_ask?: string | null; no_bid?: string | null; no_ask?: string | null; last_trade?: string | null; spread?: string | null; quote_age_seconds?: number | null; quote_status: string; quote_source_timestamp?: string | null; quote_received_timestamp?: string | null; orderbook_status: string; yes_bid_depth: string[][]; no_bid_depth: string[][]; underlying_provider?: string | null; underlying_product?: string | null; underlying_price?: string | null; underlying_age_seconds?: number | null; underlying_status: string; primary_provider?: string | null; primary_age_seconds?: number | null; secondary_provider?: string | null; secondary_instrument?: string | null; secondary_price?: string | null; secondary_bid?: string | null; secondary_ask?: string | null; secondary_status: string; settlement_followup: string; features: Record<string, Record<string, string | null>>; previous_events: Array<Record<string, string | null>>; };
export type Account = { id: string; profile: string; status: string; observed_at: string; message?: string | null; summary: { balance_cents?: number | null; portfolio_value_cents?: number | null; today_pnl_cents?: number | null; realized_pnl_cents?: number | null; fees_cents?: number | null; }; positions: Array<{ ticker: string; position?: number | null; market_exposure_cents?: number | null; realized_pnl_cents?: number | null; fees_cents?: number | null; mark_cents?: number | null; mark_status: string }>; orders: Array<{ order_id: string; ticker?: string | null; status?: string | null; side?: string | null; action?: string | null; count?: number | null; remaining_count?: number | null; yes_price_cents?: number | null; no_price_cents?: number | null; created_at?: string | null }>; fills: Array<{ trade_id: string; order_id?: string | null; ticker?: string | null; side?: string | null; action?: string | null; count?: number | null; yes_price_cents?: number | null; no_price_cents?: number | null; created_at?: string | null }>; };
export type Research = { id: string; research: Record<string, unknown>; training: Record<string, unknown>; coverage: Record<string, unknown> };
export type Admin = { id: string; health: Health; data: Record<string, unknown>; storage: Record<string, unknown>; operations: Record<string, unknown>; system: Record<string, unknown>; events: Array<Record<string, unknown>> };

const baseUrl = import.meta.env.VITE_API_BASE_URL ?? '';
async function request<T>(path: string): Promise<T> { const response = await fetch(`${baseUrl}${path}`, { credentials: 'omit' }); if (!response.ok) throw new Error(`API request failed (${response.status})`); return response.json() as Promise<T>; }

export const api = {
  health: () => request<Omit<Health, 'id'>>('/api/health'),
  markets: () => request<Omit<Market, 'id'>[]>('/api/markets'),
  market: (id: string) => request<Omit<Market, 'id'>>(`/api/markets/${encodeURIComponent(id)}`),
  account: () => request<Omit<Account, 'id'>>('/api/account?profile=production_primary'),
  research: async (): Promise<Omit<Research, 'id'>> => { const [research, training, coverage] = await Promise.all([request<Record<string, unknown>>('/api/research-data'), request<Record<string, unknown>>('/api/training'), request<Record<string, unknown>>('/api/coverage')]); return { research, training, coverage }; },
  admin: async (): Promise<Omit<Admin, 'id'>> => { const [health, data, storage, operations, system, events] = await Promise.all([api.health(), request<Record<string, unknown>>('/api/data'), request<Record<string, unknown>>('/api/storage'), request<Record<string, unknown>>('/api/operations'), request<Record<string, unknown>>('/api/system'), request<Array<Record<string, unknown>>>('/api/events?limit=20')]); return { health: { ...health, id: 'current' }, data, storage, operations, system, events }; },
};

export const dataProvider: DataProvider = {
  getList: async (resource: string) => { if (resource !== 'markets') throw new Error(`Unsupported collection: ${resource}`); const data = (await api.markets()).map((market) => ({ ...market, id: market.asset })); return { data, total: data.length } as never; },
  getOne: async (resource: string, params: GetOneParams) => { if (resource === 'overview') return { data: { ...(await api.health()), id: 'current' } } as never; if (resource === 'portfolio') return { data: { ...(await api.account()), id: 'current' } } as never; if (resource === 'research') return { data: { ...(await api.research()), id: 'current' } } as never; if (resource === 'admin') return { data: { ...(await api.admin()), id: 'current' } } as never; if (resource !== 'markets') throw new Error(`Unsupported resource: ${resource}`); const market = await api.market(String(params.id)); return { data: { ...market, id: market.asset } } as never; },
  getMany: async () => ({ data: [] }), getManyReference: async () => ({ data: [], total: 0 }),
  create: async () => { throw new Error('This terminal is read-only'); }, update: async () => { throw new Error('This terminal is read-only'); }, updateMany: async () => { throw new Error('This terminal is read-only'); }, delete: async () => { throw new Error('This terminal is read-only'); }, deleteMany: async () => { throw new Error('This terminal is read-only'); },
};
