/* eslint-disable react-refresh/only-export-components */
import { Admin, AppBar, DashboardMenuItem, Layout as AdminLayout, Menu, MenuItemLink, Resource, useGetList, useGetOne, useRedirect, useRefresh } from 'react-admin';
import { Box, Button, Card, CardContent, Chip, CircularProgress, Divider, Stack, Tab, Tabs, Typography, createTheme } from '@mui/material';
import type { ComponentProps, ReactNode } from 'react';
import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { dataProvider, type Account, type Admin as AdminRecord, type Health, type Market, type Research } from './api';
import './styles.css';

const theme = createTheme({ palette: { mode: 'dark', primary: { main: '#9b7bff' }, background: { default: '#07070a', paper: '#0d0e13' }, text: { primary: '#f3f1f8', secondary: '#92929e' } }, shape: { borderRadius: 8 }, typography: { fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif', h4: { fontWeight: 650, letterSpacing: '-0.035em' } } });
const value = (item: Record<string, unknown>, key: string) => item[key] == null ? '—' : String(item[key]);
const dollars = (cents?: number | null) => cents == null ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
const seconds = (n?: number | null) => n == null ? '—' : n <= 0 ? 'Closed' : `${Math.floor(n / 60)}m ${Math.floor(n % 60)}s`;
const age = (n?: number | null) => n == null ? '—' : `${n.toFixed(1)}s`;

function Status({ text }: { text: string }) { const bad = /error|stale|unavailable|degraded|warning|behind/i.test(text); return <Chip className={bad ? 'status warning' : 'status'} label={text.replaceAll('_', ' ')} size="small" />; }
function Metric({ label, children }: { label: string; children: ReactNode }) { return <div className="metric"><span>{label}</span><strong>{children}</strong></div>; }
function Loading() { return <Box className="terminal-loading"><CircularProgress size={24} /></Box>; }
function ErrorState({ error }: { error: unknown }) { const refresh = useRefresh(); return <Box className="terminal-loading"><Typography variant="h6">Data is unavailable</Typography><Typography color="text.secondary">{error instanceof Error ? error.message : 'The local read-only API could not be reached.'}</Typography><Button onClick={refresh}>Retry</Button></Box>; }
function Page({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { const refresh = useRefresh(); return <Box className="terminal-page"><Stack className="page-title" direction="row"><Box><Typography variant="overline">LIVE15 / LOCAL</Typography><Typography variant="h4">{title}</Typography><Typography color="text.secondary">{subtitle}</Typography></Box><Button className="quiet-button" onClick={refresh}>Refresh</Button></Stack>{children}</Box>; }

function Overview() { const health = useGetOne<Health>('overview', { id: 'current' }); const markets = useGetList<Market>('markets', { pagination: { page: 1, perPage: 20 }, sort: { field: 'asset', order: 'ASC' }, filter: {} }); const redirect = useRedirect(); if (health.isPending || markets.isPending) return <Loading />; if (health.error || markets.error || !health.data || !markets.data) return <ErrorState error={health.error ?? markets.error} />; const h = health.data; return <Page title="Overview" subtitle="Current market state, synchronized locally."><div className="overview-strip"><Status text={h.status} /><span>Recorder {h.recorder_state}</span><span>WS {h.kalshi_ws_connection_state}</span><span>{h.kalshi_ws_synchronized_count} markets synchronized</span><span>{h.kalshi_ws_seq_gaps} sequence gaps</span></div>{h.current_health_issues.length > 0 && <Card className="warning-card"><CardContent><strong>Current warnings</strong><Typography>{h.current_health_issues.join(' · ')}</Typography></CardContent></Card>}<div className="market-grid">{markets.data.map((market) => <button className="market-tile" key={market.id} onClick={() => redirect('show', 'markets', market.id)}><div><strong>{market.asset}</strong><Status text={market.lifecycle} /></div><span className="underlying">{market.underlying_price ?? market.target ?? '—'}</span><div className="quote-line"><span>YES {market.yes_bid ?? '—'} / {market.yes_ask ?? '—'}</span><span>NO {market.no_bid ?? '—'} / {market.no_ask ?? '—'}</span></div><small>{seconds(market.seconds_remaining)} · quote {age(market.quote_age_seconds)}</small></button>)}</div></Page>; }

function Markets() { const { data, isPending, error } = useGetList<Market>('markets', { pagination: { page: 1, perPage: 20 }, sort: { field: 'asset', order: 'ASC' }, filter: {} }); const redirect = useRedirect(); if (isPending) return <Loading />; if (error || !data) return <ErrorState error={error} />; return <Page title="Markets" subtitle="Authoritative current market and quote projections."><div className="terminal-table"><div className="table-head"><span>Market</span><span>Underlying</span><span>YES</span><span>NO</span><span>Remaining</span><span>State</span></div>{data.map((m) => <button className="table-row" key={m.id} onClick={() => redirect('show', 'markets', m.id)}><strong>{m.asset}<small>{m.ticker ?? 'No active ticker'}</small></strong><span>{m.underlying_price ?? '—'}<small>{m.underlying_status}</small></span><span>{m.yes_bid ?? '—'} / {m.yes_ask ?? '—'}</span><span>{m.no_bid ?? '—'} / {m.no_ask ?? '—'}</span><span>{seconds(m.seconds_remaining)}<small>quote {age(m.quote_age_seconds)}</small></span><Status text={m.lifecycle} /></button>)}</div></Page>; }

function Depth({ title, levels }: { title: string; levels: string[][] }) { return <Card className="depth"><CardContent><Typography variant="overline">{title}</Typography>{levels.length ? levels.slice(0, 8).map((row, index) => <div className="depth-row" key={`${title}-${index}`}><span>{row[0] ?? '—'}</span><span>{row[1] ?? '—'}</span></div>) : <Typography color="text.secondary">No current depth projection.</Typography>}</CardContent></Card>; }
function MarketDetail() { const id = decodeURIComponent(window.location.hash.split('/')[2] ?? ''); const { data, isPending, error } = useGetOne<Market>('markets', { id }); if (isPending) return <Loading />; if (error || !data) return <ErrorState error={error} />; return <Page title={`${data.asset} market`} subtitle={data.ticker ?? 'No active contract'}><div className="detail-hero"><Metric label="Underlying"><>{data.underlying_price ?? '—'}</></Metric><Metric label="YES"><>{data.yes_bid ?? '—'} / {data.yes_ask ?? '—'}</></Metric><Metric label="NO"><>{data.no_bid ?? '—'} / {data.no_ask ?? '—'}</></Metric><Metric label="Remaining"><>{seconds(data.seconds_remaining)}</></Metric><Metric label="Quote"><><Status text={data.quote_status} /> {age(data.quote_age_seconds)}</></Metric></div><div className="detail-grid"><Depth title="YES bid depth" levels={data.yes_bid_depth} /><Depth title="NO bid depth" levels={data.no_bid_depth} /><Card><CardContent><Typography variant="overline">Market state</Typography><Metric label="Lifecycle"><Status text={data.lifecycle} /></Metric><Metric label="Order book"><Status text={data.orderbook_status} /></Metric><Metric label="Underlying"><>{data.underlying_provider ?? '—'} · {data.underlying_status}</></Metric><Metric label="Settlement"><>{data.settlement_followup}</></Metric></CardContent></Card></div></Page>; }

function Portfolio() { const { data, isPending, error } = useGetOne<Account>('portfolio', { id: 'current' }); const [tab, setTab] = useState(0); if (isPending) return <Loading />; if (error || !data) return <ErrorState error={error} />; const content = tab === 0 ? <><div className="detail-hero"><Metric label="Balance">{dollars(data.summary.balance_cents)}</Metric><Metric label="Portfolio value">{dollars(data.summary.portfolio_value_cents)}</Metric><Metric label="Today P&L">{dollars(data.summary.today_pnl_cents)}</Metric><Metric label="Account"><Status text={data.status} /></Metric></div><Rows rows={data.positions} columns={['ticker', 'position', 'market_exposure_cents', 'realized_pnl_cents', 'mark_cents']} /></> : tab === 1 ? <Rows rows={data.orders} columns={['order_id', 'ticker', 'status', 'side', 'count', 'created_at']} /> : <Rows rows={data.fills} columns={['trade_id', 'ticker', 'side', 'count', 'yes_price_cents', 'created_at']} />; return <Page title="Portfolio" subtitle="Read-only account, orders, and fills."><Tabs value={tab} onChange={(_, next) => setTab(next)}><Tab label="Positions / Account" /><Tab label="Orders" /><Tab label="Fills" /></Tabs>{content}</Page>; }
function Rows({ rows, columns }: { rows: Array<Record<string, unknown>>; columns: string[] }) { if (!rows.length) return <Card className="empty-card"><CardContent>No verified records are currently available.</CardContent></Card>; return <div className="terminal-table"><div className="table-head">{columns.map((column) => <span key={column}>{column.replaceAll('_', ' ')}</span>)}</div>{rows.map((row, index) => <div className="table-row" key={`${index}-${value(row, columns[0])}`}>{columns.map((column) => <span key={column}>{value(row, column)}</span>)}</div>)}</div>; }

function ResearchPage() { const { data, isPending, error } = useGetOne<Research>('research', { id: 'current' }); const [tab, setTab] = useState(0); if (isPending) return <Loading />; if (error || !data) return <ErrorState error={error} />; const research = data.research; const training = data.training; const coverage = data.coverage; return <Page title="Research" subtitle="Authority, coverage, and gated training evidence."><Tabs value={tab} onChange={(_, next) => setTab(next)}><Tab label="Authority" /><Tab label="Coverage" /><Tab label="Training" /></Tabs>{tab === 0 && <div className="metric-grid-wide"><Metric label="Research universe">{value(research, 'universe_id')}</Metric><Metric label="Eligible events">{value(research, 'eligible_events')}</Metric><Metric label="Eligible observations">{value(research, 'eligible_observations')}</Metric><Metric label="Holdout access">{value(research, 'holdout_accessed')}</Metric></div>}{tab === 1 && <div className="metric-grid-wide"><Metric label="Coverage status">{value(coverage, 'status')}</Metric><Metric label="Finalized events">{value(coverage, 'finalized_events')}</Metric><Metric label="Trainable events">{value(coverage, 'trainable_events')}</Metric><Metric label="Training rows">{value(coverage, 'training_rows')}</Metric></div>}{tab === 2 && <div className="metric-grid-wide"><Metric label="Sequence readiness">{value(training, 'sequence_readiness')}</Metric><Metric label="Current trainable">{value((training.current_trainable ?? {}) as Record<string, unknown>, 'status')}</Metric><Metric label="Completed dataset">{value((training.latest_completed_dataset ?? {}) as Record<string, unknown>, 'status')}</Metric><Metric label="Training controls">Gated / not exposed</Metric></div>}</Page>; }

function AdminPage() { const { data, isPending, error } = useGetOne<AdminRecord>('admin', { id: 'current' }); const [tab, setTab] = useState(0); if (isPending) return <Loading />; if (error || !data) return <ErrorState error={error} />; const panel = tab === 0 ? data.data : tab === 1 ? data.storage : tab === 2 ? data.operations : data.system; return <Page title="Admin" subtitle="Owner-only, read-only operational projections."><Tabs value={tab} onChange={(_, next) => setTab(next)}><Tab label="Data" /><Tab label="Storage" /><Tab label="Operations" /><Tab label="System" /></Tabs><div className="admin-grid">{Object.entries(panel).slice(0, 18).map(([key, item]) => <Metric key={key} label={key.replaceAll('_', ' ')}>{typeof item === 'object' ? JSON.stringify(item) : String(item ?? '—')}</Metric>)}</div>{tab === 2 && <Card><CardContent><Typography variant="overline">Recent warnings / events</Typography>{data.events.length ? data.events.slice(0, 10).map((event: Record<string, unknown>, index: number) => <div className="event-row" key={index}><Status text={value(event, 'severity')} /><span>{value(event, 'event_type')}</span><span>{value(event, 'message')}</span></div>) : <Typography color="text.secondary">No retained events.</Typography>}</CardContent></Card>}</Page>; }

function TerminalMenu() { return <Menu><DashboardMenuItem primaryText="Overview" /><Divider /><MenuItemLink to="/markets" primaryText="Markets" /><MenuItemLink to="/portfolio" primaryText="Portfolio" /><MenuItemLink to="/research" primaryText="Research" /><MenuItemLink to="/admin" primaryText="Admin" /></Menu>; }
function TerminalBar() { return <AppBar><Typography className="terminal-brand">LIVE15 <span>TERMINAL</span></Typography></AppBar>; }
function TerminalLayout(props: ComponentProps<typeof AdminLayout>) { return <AdminLayout {...props} appBar={TerminalBar} menu={TerminalMenu} />; }
function App() { return <Admin title="LIVE15 Terminal" theme={theme} dataProvider={dataProvider} dashboard={Overview} layout={TerminalLayout} requireAuth={false}><Resource name="markets" list={Markets} show={MarketDetail} /><Resource name="portfolio" list={Portfolio} /><Resource name="research" list={ResearchPage} /><Resource name="admin" list={AdminPage} /></Admin>; }

const root = document.getElementById('root')!; if (!root.dataset.mounted) { root.dataset.mounted = 'true'; createRoot(root).render(<App />); }
